"""
Indicates that an Input Object is a OneOf Input Object (and thus requires exactly one of its field be provided)
"""
directive @oneOf on INPUT_OBJECT

"""
Provides a scalar specification URL for specifying the behavior of custom scalar types.
"""
directive @specifiedBy(
  """URL that specifies the behavior of this scalar."""
  url: String!
) on SCALAR

input BooleanFilter {
  eq: Boolean
}

scalar DateTime

input DateTimeFilter {
  eq: DateTime
  gt: DateTime
  lt: DateTime
  ge: DateTime
  le: DateTime
  in: [DateTime]
}

type Mutation {
  createTodo(input: TodoInput!): Todo
  updateTodo(id: ID!, input: TodoInput!): Boolean
  deleteTodo(id: ID!): Boolean
}

type MutationEvent {
  type: String!
  uid: ID!
  mutation: MutationType!
}

enum MutationType {
  CREATE
  UPDATE
  DELETE
}

type Query {
  queryTodo(filter: TodoFilter, sort: TodoSort, first: Int, after: String): [Todo]
  getTodo(id: ID): Todo
}

enum SortDirection {
  ASC
  DESC
}

input StringFilter {
  eq: String
  contains: String
  allofterms: String
  anyofterms: String
  alloftext: String
  anyoftext: String
  lt: String
  le: String
  gt: String
  ge: String
  in: [String]
}

type Subscription {
  event(types: [String]): MutationEvent!
}

type Todo {
  uid: ID!
  id: ID!
  title: String
  completed: Boolean
  createdAt: DateTime
}

input TodoFilter {
  title: StringFilter
  completed: BooleanFilter
  createdAt: DateTimeFilter
  and: [TodoFilter]
  or: [TodoFilter]
  not: TodoFilter
}

input TodoInput {
  uid: ID
  title: String
  completed: Boolean
  createdAt: DateTime
}

input TodoSort {
  title: SortDirection
  completed: SortDirection
  createdAt: SortDirection
}

