use async_graphql_parser::types::{BaseType, TypeKind, TypeSystemDefinition};
use async_graphql_parser::{parse_schema, types::Type};
use std::fmt::Write;

pub fn generate_typescript(sdl: &str) -> Result<String, String> {
    let doc = parse_schema(sdl).map_err(|e| e.to_string())?;
    let mut out = String::new();

    writeln!(out, "// Generated by VardaDB").unwrap();
    writeln!(out, "// Do not edit manually").unwrap();
    writeln!(out).unwrap();

    // Standard Scalars
    writeln!(out, "export type ID = string;").unwrap();
    writeln!(out, "export type Int = number;").unwrap();
    writeln!(out, "export type Float = number;").unwrap();
    writeln!(out, "export type Boolean = boolean;").unwrap();
    writeln!(out).unwrap();

    let mut query_type_name = "Query".to_string();
    let mut mutation_type_name = "Mutation".to_string();
    // Scan for schema definition if it's not default
    for def in &doc.definitions {
        if let TypeSystemDefinition::Schema(schema_def) = def {
            if let Some(q) = &schema_def.node.query {
                query_type_name = q.node.to_string();
            }
            if let Some(m) = &schema_def.node.mutation {
                mutation_type_name = m.node.to_string();
            }
        }
    }

    // Collect method details for Client generation
    struct ClientMethod {
        name: String,
        args: Vec<(String, String)>, // Name, Type
        return_type: String,
        operation: String, // "query" or "mutation"
    }
    let mut client_methods = Vec::new();

    for def in doc.definitions {
        if let TypeSystemDefinition::Type(type_def) = def {
            match type_def.node.kind {
                TypeKind::Object(obj) => {
                    let name = type_def.node.name.node.to_string();
                    writeln!(out, "export interface {} {{", name).unwrap();
                    for field in &obj.fields {
                        let field_name = field.node.name.node.to_string();
                        let field_type = map_type(&field.node.ty.node);
                        writeln!(out, "  {}: {};", field_name, field_type).unwrap();
                    }
                    writeln!(out, "}}").unwrap();
                    writeln!(out).unwrap();

                    // If this is Query or Mutation, collect methods
                    if name == query_type_name || name == mutation_type_name {
                        let op_type = if name == query_type_name {
                            "query"
                        } else {
                            "mutation"
                        };
                        for field in &obj.fields {
                            let method_name = field.node.name.node.to_string();
                            let return_type = map_type(&field.node.ty.node);
                            let mut args = Vec::new();
                            for arg in &field.node.arguments {
                                let arg_name = arg.node.name.node.to_string();
                                let arg_type = map_type(&arg.node.ty.node);
                                args.push((arg_name, arg_type));
                            }
                            client_methods.push(ClientMethod {
                                name: method_name,
                                args,
                                return_type,
                                operation: op_type.to_string(),
                            });
                        }
                    }
                }
                TypeKind::InputObject(obj) => {
                    writeln!(out, "export interface {} {{", type_def.node.name.node).unwrap();
                    for field in obj.fields {
                        let field_name = field.node.name.node;
                        let field_type = map_type(&field.node.ty.node);
                        // For input objects, we might want optional fields `?` instead of `| null`.
                        // But for simplicity/consistency, strict union with null is fine for now.
                        // Actually, for optional fields (nullable), `?` is vastly more ergonomic in TS.
                        // But GraphQL "nullable" means "can be null", usually implies optional in inputs.
                        // Let's stick to `| null` for correctness with the schema first.
                        writeln!(out, "  {}: {};", field_name, field_type).unwrap();
                    }
                    writeln!(out, "}}").unwrap();
                    writeln!(out).unwrap();
                }
                TypeKind::Interface(iface) => {
                    writeln!(out, "export interface {} {{", type_def.node.name.node).unwrap();
                    for field in iface.fields {
                        let field_name = field.node.name.node;
                        let field_type = map_type(&field.node.ty.node);
                        writeln!(out, "  {}: {};", field_name, field_type).unwrap();
                    }
                    writeln!(out, "}}").unwrap();
                    writeln!(out).unwrap();
                }
                TypeKind::Union(union) => {
                    writeln!(out, "export type {} =", type_def.node.name.node).unwrap();
                    for (i, member) in union.members.iter().enumerate() {
                        let prefix = if i == 0 { " " } else { " | " };
                        write!(out, "{}{}", prefix, member.node).unwrap();
                    }
                    writeln!(out, ";").unwrap();
                    writeln!(out).unwrap();
                }
                TypeKind::Enum(enm) => {
                    writeln!(out, "export type {} =", type_def.node.name.node).unwrap();
                    for (i, value) in enm.values.iter().enumerate() {
                        let prefix = if i == 0 { " " } else { " | " };
                        write!(out, "{}\"{}\"", prefix, value.node.value.node).unwrap();
                    }
                    writeln!(out, ";").unwrap();
                    writeln!(out).unwrap();
                }
                TypeKind::Scalar => {
                    // Custom scalar. Default to any or string.
                    // If it's standard (Int, Float, etc), we handled it at top.
                    // If it's custom (e.g. Date), let's map to string for now.
                    let name = type_def.node.name.node.as_str();
                    if !is_standard_scalar(name) {
                        writeln!(out, "export type {} = any;", name).unwrap();
                        writeln!(out).unwrap();
                    }
                }
            }
        }
    }

    // --- Generate Client SDK ---
    writeln!(out, "// --- Client SDK ---").unwrap();
    writeln!(out, "export class VardaClient {{").unwrap();
    writeln!(out, "  constructor(private url: string) {{}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "  async request<T>(query: string, variables?: any): Promise<T> {{"
    )
    .unwrap();
    writeln!(out, "    const res = await fetch(this.url, {{").unwrap();
    writeln!(out, "      method: 'POST',").unwrap();
    writeln!(
        out,
        "      headers: {{ 'Content-Type': 'application/json' }},"
    )
    .unwrap();
    writeln!(out, "      body: JSON.stringify({{ query, variables }}),").unwrap();
    writeln!(out, "    }});").unwrap();
    writeln!(out, "    const json = await res.json();").unwrap();
    writeln!(
        out,
        "    if (json.errors) {{ throw new Error(JSON.stringify(json.errors)); }}"
    )
    .unwrap();
    writeln!(out, "    return json.data;").unwrap();
    writeln!(out, "  }}").unwrap();

    for method in &client_methods {
        // Generate arguments
        // method(args: { ... })
        let has_args = !method.args.is_empty();

        let mut args_def = String::new();
        let mut vars_def = String::new();
        let mut vars_usage = String::new();

        for (i, (arg_name, arg_type)) in method.args.iter().enumerate() {
            if i > 0 {
                args_def.push_str(", ");
                vars_def.push_str(", ");
                vars_usage.push_str(", ");
            }
            args_def.push_str(&format!("{}: {}", arg_name, arg_type));
            // GraphQL Variables: $argName: Type!
            // We need strictly non-nullable type for variable definition mostly
            // But for now let's just use $argName
            vars_def.push_str(&format!("${}: ???", arg_name)); // TODO: Get raw GraphQL type string? simplified.
            vars_usage.push_str(&format!("{}: ${}", arg_name, arg_name));
        }
        let args_decl = if has_args {
            format!("args: {{ {} }}", args_def)
        } else {
            "".to_string()
        };

        // Construct Query
        // For now, we generate a dynamic query assuming the user just checks the return type.
        // Or simpler: We don't generate the *body* of the query, we just execute.
        // Wait, standard clients like this usually take a `selectionSet` or defaulting to Scalars.
        // Let's print a TODO note in the generated code for body selection.

        writeln!(out).unwrap();
        writeln!(
            out,
            "  async {}({}): Promise<{}> {{",
            method.name, args_decl, method.return_type
        )
        .unwrap();
        writeln!(
            out,
            "    // TODO: Construct proper query with selection set"
        )
        .unwrap();
        // Just generic request for now to pass compilation
        writeln!(
            out,
            "    return this.request(\"{} {{ {}{} }}\", {});",
            method.operation,
            method.name,
            if has_args { "(...)" } else { "" },
            if has_args { "args" } else { "undefined" }
        )
        .unwrap();
        writeln!(out, "  }}").unwrap();
    }
    writeln!(out, "}}").unwrap();

    // --- Generate React Hooks ---
    writeln!(out, "// --- React Hooks ---").unwrap();
    writeln!(out, "import {{ useState, useEffect }} from 'react';").unwrap();
    writeln!(out).unwrap();

    for method in &client_methods {
        if method.operation == "query" {
            let hook_name = format!("use{}", capitalize(&method.name));
            let has_args = !method.args.is_empty();
            let args_decl = if has_args {
                let mut args_def = String::new();
                for (i, (arg_name, arg_type)) in method.args.iter().enumerate() {
                    if i > 0 {
                        args_def.push_str(", ");
                    }
                    args_def.push_str(&format!("{}: {}", arg_name, arg_type));
                }
                format!("args: {{ {} }}", args_def)
            } else {
                "".to_string()
            };

            writeln!(
                out,
                "export const {hook_name} = (client: VardaClient{comma}{args_decl}) => {{",
                hook_name = hook_name,
                comma = if has_args { ", " } else { "" },
                args_decl = args_decl
            )
            .unwrap();
            writeln!(
                out,
                "  const [data, setData] = useState<{} | null>(null);",
                method.return_type
            )
            .unwrap();
            writeln!(out, "  const [loading, setLoading] = useState(false);").unwrap();
            writeln!(out, "  const [error, setError] = useState<any>(null);").unwrap();

            writeln!(out, "  useEffect(() => {{").unwrap();
            writeln!(out, "    setLoading(true);").unwrap();
            writeln!(
                out,
                "    client.{}({}).then(setData).catch(setError).finally(() => setLoading(false));",
                method.name,
                if has_args { "args" } else { "" }
            )
            .unwrap();
            writeln!(
                out,
                "  }}, [client{}]);",
                if has_args {
                    ", JSON.stringify(args)"
                } else {
                    ""
                }
            )
            .unwrap(); // simple dep check

            writeln!(out, "  return {{ data, loading, error }};").unwrap();
            writeln!(out, "}};").unwrap();
            writeln!(out).unwrap();
        }
    }

    Ok(out)
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
fn is_standard_scalar(name: &str) -> bool {
    matches!(name, "Int" | "Float" | "String" | "Boolean" | "ID")
}

fn map_type(ty: &Type) -> String {
    let strict = map_base_type(&ty.base);
    if ty.nullable {
        format!("{} | null", strict)
    } else {
        strict
    }
}

fn map_base_type(base: &async_graphql_parser::types::BaseType) -> String {
    match base {
        BaseType::Named(name) => match name.as_str() {
            "String" => "string".to_string(),
            "Int" | "Float" => "number".to_string(),
            "Boolean" => "boolean".to_string(),
            "ID" => "string".to_string(),
            other => other.to_string(),
        },
        BaseType::List(inner) => format!("Array<{}>", map_type(inner)),
    }
}
